#!/bin/bash
# Build the Mac App Store edition: sandboxed app, LGPL media engine as a signed helper.
#
# Without signing settings, the app is ad-hoc signed with the MAS entitlements for local sandbox
# testing only. With them, it is signed for App Store distribution and packaged as an installer .pkg.
# This script never uploads anything. --validate asks App Store Connect to validate the .pkg only.
#
# Signing settings come from the environment or from the ignored file macOS/Signing/mas.local.env:
#   CONVERTY_MAS_TEAM_ID             Apple Developer team ID
#   CONVERTY_MAS_APP_IDENTITY        "Apple Distribution: <name> (<team ID>)"
#   CONVERTY_MAS_INSTALLER_IDENTITY  "3rd Party Mac Developer Installer: <name> (<team ID>)"
#   CONVERTY_MAS_PROFILE             path to the Mac App Store provisioning profile
#   CONVERTY_ASC_KEY_ID, CONVERTY_ASC_ISSUER_ID  App Store Connect API key, for --validate only
set -euo pipefail
native_root="$(cd "$(dirname "$0")/.." && pwd)"
repo_root="$(dirname "$native_root")"
validate=false
[[ "${1:-}" == '--validate' ]] && validate=true
[[ -f "$native_root/Signing/mas.local.env" ]] && source "$native_root/Signing/mas.local.env"

engine_root="${CONVERTY_MAS_ENGINE_DIR:-}"
if [[ -z "$engine_root" || ! -f "$engine_root/provenance.json" ]]; then
    echo 'Set CONVERTY_MAS_ENGINE_DIR to a work directory from: build-engine.py --variant lgpl' >&2
    exit 1
fi
engine="$engine_root/prefix/bin/ffmpeg"
python3 - "$engine_root" "$engine" <<'PY'
import hashlib, json, pathlib, subprocess, sys
root, engine = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
record = json.loads((root / 'provenance.json').read_text())
if record.get('variant') != 'lgpl':
    raise SystemExit('The Mac App Store build requires the LGPL engine variant.')
if hashlib.sha256(engine.read_bytes()).hexdigest() != record['ffmpeg_sha256']:
    raise SystemExit('Engine does not match its source-build provenance.')
configuration = subprocess.check_output([str(engine), '-hide_banner', '-buildconf'], text=True)
if any(flag in configuration for flag in ['--enable-gpl', '--enable-nonfree', 'libx264']):
    raise SystemExit('Engine configuration includes a GPL or nonfree component.')
PY

mkdir -p "$native_root/Helpers"
cp "$engine" "$native_root/Helpers/ffmpeg"
chmod +x "$native_root/Helpers/ffmpeg"
cp "$repo_root/LICENSE" "$native_root/Resources/LICENSE.txt"
"$engine" -version > "$native_root/Resources/FFmpeg-build.txt"
shasum -a 256 "$engine" | awk '{print $1 "  ffmpeg (build input)"}' >> "$native_root/Resources/FFmpeg-build.txt"
cp "$engine_root/notices/All-Licenses.txt" "$native_root/Resources/MediaEngineNotices.txt"
cp "$engine_root/notices/sources.json" "$native_root/Resources/MediaEngineSources.json"
cp "$engine_root/provenance.json" "$native_root/Resources/MediaEngineProvenance.json"

xcodegen generate --spec "$native_root/project.yml"
xcodebuild -project "$native_root/Converty.xcodeproj" -scheme Converty-MAS -configuration Release \
    -derivedDataPath "$native_root/.build/xcode-mas" build
output="$repo_root/dist-native/mas"
app="$output/Converty.app"
mkdir -p "$output"
rm -rf "$app" # Generated by this script; sources and user files are never removed.
ditto "$native_root/.build/xcode-mas/Build/Products/Release/Converty.app" "$app"
helper="$app/Contents/Helpers/ffmpeg"
[[ -x "$helper" ]] || { echo 'The app is missing its media engine helper.' >&2; exit 1; }

version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$app/Contents/Info.plist")"
bundle_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$app/Contents/Info.plist")"
if [[ -n "${CONVERTY_MAS_APP_IDENTITY:-}" ]]; then
    : "${CONVERTY_MAS_TEAM_ID:?Set CONVERTY_MAS_TEAM_ID}" "${CONVERTY_MAS_INSTALLER_IDENTITY:?Set CONVERTY_MAS_INSTALLER_IDENTITY}" "${CONVERTY_MAS_PROFILE:?Set CONVERTY_MAS_PROFILE}"
    profile_plist="$(mktemp)"
    entitlements="$(mktemp)"
    trap 'rm -f "$profile_plist" "$entitlements"' EXIT
    security cms -D -i "$CONVERTY_MAS_PROFILE" > "$profile_plist"
    python3 - "$profile_plist" "$native_root/Signing/Converty-MAS.entitlements" "$entitlements" "$CONVERTY_MAS_TEAM_ID" "$bundle_id" <<'PY'
import plistlib, sys
profile = plistlib.load(open(sys.argv[1], 'rb'))
base = plistlib.load(open(sys.argv[2], 'rb'))
team, bundle_id = sys.argv[4], sys.argv[5]
granted = profile.get('Entitlements', {})
if team not in profile.get('TeamIdentifier', []):
    raise SystemExit(f'The provisioning profile belongs to {profile.get("TeamName")}, not team {team}.')
if granted.get('com.apple.application-identifier') != f'{team}.{bundle_id}':
    raise SystemExit(f'The provisioning profile is for {granted.get("com.apple.application-identifier")}, not {team}.{bundle_id}.')
if 'ProvisionedDevices' in profile or profile.get('ProvisionsAllDevices'):
    raise SystemExit('Use a Mac App Store distribution profile, not a development or Developer ID profile.')
base['com.apple.application-identifier'] = f'{team}.{bundle_id}'
base['com.apple.developer.team-identifier'] = team
plistlib.dump(base, open(sys.argv[3], 'wb'))
PY
    cp "$CONVERTY_MAS_PROFILE" "$app/Contents/embedded.provisionprofile"
    codesign --force --sign "$CONVERTY_MAS_APP_IDENTITY" --options runtime --timestamp \
        --entitlements "$native_root/Signing/FFmpeg-MAS.entitlements" "$helper"
    codesign --force --sign "$CONVERTY_MAS_APP_IDENTITY" --options runtime --timestamp \
        --entitlements "$entitlements" "$app"
else
    echo 'No Mac App Store signing identity configured: ad-hoc signing for local sandbox testing only.'
    codesign --force --sign - --options runtime --entitlements "$native_root/Signing/FFmpeg-MAS.entitlements" "$helper"
    codesign --force --sign - --options runtime --entitlements "$native_root/Signing/Converty-MAS.entitlements" "$app"
fi

codesign --verify --deep --strict --verbose=2 "$app"
python3 - "$app" "$helper" <<'PY'
import plistlib, subprocess, sys
def entitlements(path):
    data = subprocess.run(['codesign', '-d', '--entitlements', '-', '--xml', path], capture_output=True, check=True).stdout
    return plistlib.loads(data) if data else {}
app, helper = entitlements(sys.argv[1]), entitlements(sys.argv[2])
if app.get('com.apple.security.app-sandbox') is not True or helper.get('com.apple.security.app-sandbox') is not True:
    raise SystemExit('The app and its helper must both be sandboxed.')
if helper.get('com.apple.security.inherit') is not True or len(helper) != 2:
    raise SystemExit('The helper must have exactly app-sandbox and inherit entitlements.')
if any(key.startswith('com.apple.security.network') for key in app):
    raise SystemExit('Converty makes no network requests and must not request network entitlements.')
print('Entitlements verified:', ', '.join(sorted(app)))
PY

if [[ -z "${CONVERTY_MAS_APP_IDENTITY:-}" ]]; then
    echo "Built $app (ad-hoc, not for submission)"
    exit 0
fi
pkg="$output/Converty-$version-mas.pkg"
rm -f "$pkg"
productbuild --component "$app" /Applications --sign "$CONVERTY_MAS_INSTALLER_IDENTITY" "$pkg"
pkgutil --check-signature "$pkg"
echo "Built $pkg"
if $validate; then
    : "${CONVERTY_ASC_KEY_ID:?Set CONVERTY_ASC_KEY_ID}" "${CONVERTY_ASC_ISSUER_ID:?Set CONVERTY_ASC_ISSUER_ID}"
    xcrun altool --validate-app -f "$pkg" -t macos --apiKey "$CONVERTY_ASC_KEY_ID" --apiIssuer "$CONVERTY_ASC_ISSUER_ID"
fi
